### PR TITLE
Add Author Extractor

### PR DESCRIPTION
**Pull request by erikreedstrom**
- added Author class
- added PostAuthor class
- updated blog to include Author array
- updated post to include Author link
- added tests

## Why Its Required
For sites with multiple contributors, it is necessary to capture the author's information on export from WordPress so the information may be migrated to Contentful.

## Technique
Unfortunately, while WordPress lists all contributors with id as part of the export, it only references the username on the post under `<dc:creator>`. We cross reference this with the authors listed and extract the id accordingly.

### CODE REVIEW

**Comment by markhealey** [comment]
:+1:

**Comment by erikreedstrom** [comment]
I think I'm missing something here. How are collections generated?

**Comment by dlitvakb** [comment]
Hey @erikreedstrom,

Thank you very much for the Contribution!

I'll look into it and try to get it released as soon as possible

Cheers

**Comment by dlitvakb** [comment]
Hey @erikreedstrom,

Sorry for the delay in getting this merged. Our WordPress expert is a bit busy, trying to get it reviewed this week.

Cheers

**Comment by realityking** [comment]
I tested it with some sample data, the output looks good to me. :+1: from my side.

**Pull request merged**
